### ISSUE TITLE
semux-gui started slowly

### ISSUE THREAD

**Issue by jezzmemo** [semuxproject/semux#545]
Hi there,

#### System information

Semux version: `v1.0.0`

OS & Version: `macOS 10.12.6 `

Java Version:`java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)`

#### Expected behaviour

semux-gui started quickly

#### Actual behaviour

semux-gui started slowly

#### Steps to reproduce the behaviour

run  `./semux-gui.sh` shell,I need to wait 5 seconds or 10 seconds.

RC4 and RC5 Version started quickly,please improve performance.

**Comment by semuxproject** [comment]
I believe this is due to https://github.com/semuxproject/semux/blob/4a83a2d527f5fe87e6a311d56faced96341d1230/src/main/java/org/semux/net/NodeManager.java#L95

This 5 seconds delay was originally introduced to make sure the IP address is properly initialized asynchronously.

Better approach is to start searching seed nodes right after IP is updated.

**Comment by jezzmemo** [comment]
Process the sync after open the wallet UI.

**Do not block the main thread.**

**Comment by orogvany** [comment]
Should be able to close this now that splash screen is added.

**Comment by cryptokat** [comment]
resolved by #744
