### ISSUE TITLE
Launching Semux Client via Java WebStart

### ISSUE THREAD

**Issue by witoldsz** [semuxproject/semux#719]
We should consider using Java WebStart, a convenient way of launching Java desktop applications. 
Now, the "Getting Started" section of semux.info page looks like this:

1. Download and install Java SE Runtime Environment 8;
2. Download the Latest Release and unpack it to a desired directory;
3. Run semux.exe if you're on Windows; or run ./semux-gui.sh if you're on Linux or macOS.
4. (Windows users) You may also need to download Microsoft Visual C++ 2010 Redistributable Package 32-bit or 64-bit
5. Get ready to join the Mainnet Starting in Q1 2018.

With Java WebStart it could look like this:
1. Download and install Java SE Runtime Environment 8;
2. Click `here` to install and launch the Semux Client
3. Get ready to join the Mainnet Starting in Q1 2018.

There is also a separate case: launching from a command line (or when there is no browser plugin for JWS), which looks like this:
`$ jre/bin/javaws http://semux.info/semux.jnlp`

As far as I can see, we could have a `semux.jnlp` file which is always updated to reference the most recent version of the client, and also a `semux-v1.0.0.jnlp`, `semux-v1.0.1.jnlp`, etc…

What do you think about it?

**Comment by cryptokat** [comment]
This wouldn't be an option as Java Web Start has been deprecated since Java 9 and is going to be discontinued in Java 11 which will be released in September 2018.

Source
- http://www.oracle.com/technetwork/java/javase/9-deprecated-features-3745636.html
- http://www.oracle.com/technetwork/java/javase/javaclientroadmapupdate2018mar-4414431.pdf
