### ISSUE TITLE
Security weakness in wallet encryption

### ISSUE THREAD

**Issue by fransla** [semuxproject/semux#758]
The user-supplied password is used in a single round of Blake2b to generate the aes key used for encrypting the private key in the wallet.dat file:
`byte[] key = Hash.h256(Bytes.of(password));`
As Blake2b is even faster than SHA1 or MD5, it means that millions of passwords a second can be tried on a given wallet.dat file; this means that any password likely chosen by a normal user would be easily brute-forced if their wallet.dat file was stolen.

Compare that to the Bitcoin wallet.dat encryption:
It also uses AES for the actual encryption, but uses at least 25000 rounds of hashing to get the key:
```
                if (pMasterKey.second.nDeriveIterations < 25000)
                    pMasterKey.second.nDeriveIterations = 25000;
```

This means that the Semux wallet.dat is significantly (several orders of a magnitude) less resistant to  brute force attacks on the password.

Suggested fix:
Increase the number of rounds of hashing to at least 100 000, as hardware is faster, and do not allow users to enter passwords shorter than 10 characters. Ideally, the passwords should also be checked against known breach lists such as https://haveibeenpwned.com/Passwords

**Comment by semuxdev** [comment]
Let's bump the wallet version to `3` and add this enhancement.

**Comment by orogvany** [comment]
I don't think we should enforce passwords must be > 10 chars.  Password security is really up to the user, and forming the data to our standards isn't great.  On an otherwise secure system, password encryption doesn't really add otherwise security.

Also, for testnet, I like my 0 char password for development :D  Even bitcoin does not enforce passworded or minimum password length.

Otherwise, I completely agree.
