### ISSUE TITLE
Simplify  Semux API

### ISSUE THREAD

**Issue by semuxdev** [semuxproject/semux#780]
My web knowledge is outdated, but I'm not liking the way semux API evolves. It's getting more and more complex and confusing.

1. The URIs of API endpoints are not consistent. I believe this is due to the migration from v1 to v2. Majority of them has been changed to conform the REST guidelines while others are still in RPC standards.
2. Different HTTP methods, GET and POST, have been introduced to distinguish state and state-less operations. The days when you type the full request in browser is gone.
3. If we introduce EVM, how are developers going to interact with our API? Are we going to continue REST or define our own standards?

**References**
Bitcoin API: https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list#Full_list
Ethereum API: https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-methods

**Comment by cryptokat** [comment]
> The URIs of API endpoints are not consistent. I believe this is due to the migration from v1 to v2. Majority of them has been changed to conform the REST guidelines while others are still in RPC standards.
> The days when you type the full request in browser is gone.

That's the whole point of providing a standard swagger spec. With a swagger.json, developers can automatically generate an API client for each of their favorite languages, which makes the naming of URIs less relevant to the API's usability.

Plus Swagger UI provides a user friendly way for developers & end-users to interact with the API without manually composing URLs and writing a single line of code.

**Comment by orogvany** [comment]
I for one prefer full requests in URLs for services that are meant for local running, but I understand the reasons to distinguish POST/GET.  The original HTTP defined this 'safe' method as convention, and it's easier to work with as a dev with curls/browsers.  AFAIK, the http/2 spec dropped the discussion of it entirely (or maybe the intent is that the semantics of it are unchanged since 1.1 spec so are left out?).

Swagger generation is nice to bootstrap, but hand interaction is still a thing.  

eth does everything as a POST, regardless of its mutability of the wallet state.  I agree we should discuss what our goals are for the api, and what ideal usage looks like.  I'm fine with the changes, as long as we present a consistent interface.

**Comment by cryptokat** [comment]
> I for one prefer full requests in URLs for services
@orogvany API 2.0 keeps all request parameters in query string. `-X POST` is the only thing you need to add if you are a cURL user. For browser users there is a nicely styled Swagger UI, that makes it pointless to manually compose URLs.

**Comment by orogvany** [comment]
Ah, sorry, I guess I wasn't up to date with latest state of the 2.0 API.  thanks for the clarification!

**Comment by semuxdev** [comment]
Never mind my dumb complaints. Swagger is definitely a cool tool. Let's move on!
